"""
Train RSSM AWARE or Transformer AWARE on a dataset generated by scripts/generate_data.py.

  python scripts/train.py model=rssm_aware dataset_path=data/sim/<date>/<time>
  python scripts/train.py model=transformer_aware dataset_path=data/sim/<date>/<time>
"""
import os
os.environ.setdefault("MUJOCO_GL", "egl") # headless rendering, set before importing mujoco

import hydra
from omegaconf import DictConfig

from aware.utils.logger import init_logging

@hydra.main(config_path="../configs", config_name="train", version_base=None)
def main(cfg: DictConfig):

  # create the run folder and logger, and save the configs
  logger, cfg = init_logging(cfg)

  model = hydra.utils.instantiate(cfg.model)
  trainer = hydra.utils.instantiate(cfg.trainer, model=model, logger=logger)
  trainer.train()

if __name__ == "__main__":
  main()
